const INCREASE = 'INCREASE'
const DECREASE = 'DECREASE'
const GET_TOTAL = 'GET_TOTAL'
const REMOVE = 'REMOVE'
const GET_AMOUNT = 'GET_AMOUNT'
const CLEAR_CART = 'CLEAR_CART'

export { INCREASE, DECREASE, GET_TOTAL, REMOVE, GET_AMOUNT, CLEAR_CART }
