const INCREASE = 'INCREASE'
const DECREASE = 'DECREASE'
const GET_TOTALS = 'GET_TOTALS'
const REMOVE = 'REMOVE'
const GET_AMOUNT = 'GET_AMOUNT'
const CLEAR_CART = 'CLEAR_CART'

export { INCREASE, DECREASE, GET_TOTALS, REMOVE, GET_AMOUNT, CLEAR_CART }
